# vim: ft=yaml
os:
  - linux
  - osx

sudo: required
language: bash

env:
  - TRAVIS_BASH_VERSION="4.1" TRAVIS_GIT_VERSION="1.8.0"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./tests/integ-tests/install-linux-deps.sh; fi;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./tests/integ-tests/install-osx-deps.sh; fi;

script:
    - ./tests/integ-tests/integ-tests.sh
